---
framework: jest
licenseTier: xsmall
postMerge: 
  pattern: 
    - "./test/unit/*.test.tsx"
    - "./test/unit/*.test.ts"
    - "./test/*.test.tsx"
preMerge:
  pattern:
    - "./test/unit/*.test.tsx"
    - "./test/unit/*.test.ts"
    - "./test/*.test.tsx"
preRun:
     command:
        - yarn install
        - yarn run clean
        - yarn run build
postRun:
     command:
        - yarn --version
version: 1.0